### ISSUE TITLE
Bug image with-puppeter

### ISSUE THREAD

**Issue by OscarSotoSanchez** [Zenika/alpine-chrome#18]
Hi, you have a bug in the docker image with-puppeter, if you don't add a path "/usr/src/app" in the command "npm install", you will recived a error message in the execution.

 module.js:549
    throw err;
    ^

Error: Cannot find module 'puppeteer'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/src/app/pdf.js:1:81)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

Then, if you modify the command for "RUN npm install /usr/src/app" you will resolved the problem. Best regards.

**Comment by jlandure** [comment]
Hi @OscarSotoSanchez 👋 
Thanks for your report!

I will have a look but normally the workdir is already set in the Dockerfile.
`WORKDIR /usr/src/app`

Can you describe your docker container launch command? Thanks! 👍

**Comment by jlandure** [comment]
For you information @OscarSotoSanchez, I've set the `WORKDIR` instruction at the beginning of the `Dockerfile`.

**Comment by jlandure** [comment]
@all-contributors please add @OscarSotoSanchez for bug
